name: Deploy Chat Services to EC2

on:
  push:
    branches:
      - test  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
    - name: Set up SSH key for EC2
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_PEM_KEY }}

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker images for add and get friends services
      run: |
        docker build -t kamartinez/chat-service

    - name: Push images to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push kamartinez/chat-service

    - name: Deploy services to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 34.231.95.89
        username: ec2-user
        key: ${{ secrets.EC2_PEM_KEY }}
        script: |
          docker stop chat-service || true
          docker rm chat-service || true

          docker pull kamartinez/chat-service

          docker run -d --name chat-service -p 8000:8000 kamartinez/chat-service
