name: Deploy Chat Service to EC2

on:
  push:
    branches: [ test ]  # Puedes cambiar a 'main' si es tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_PEM_KEY }}" > ~/.ssh/ec2.pem
        chmod 600 ~/.ssh/ec2.pem

    - name: Deploy Docker container on EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2.pem ec2-user@54.147.166.156 << 'EOF'
          docker pull kamartinez/chat-service:latest
          docker stop chat-service || true
          docker rm chat-service || true
          docker run -d --name chat-service -p 8000:8000 kamartinez/chat-service:latest
        EOF
